### ISSUE TITLE
Questions about prior art and specific mappings

### ISSUE THREAD

**Issue by chris-counteractive** [mitre-attack/attack-datasources#2]
Thank you for this! We love ATT&CK, but the data sources sections have always felt a bit "loose" and left mostly as an exercise for the reader.  The blog series and this repo prompted a couple questions I hoped you could discuss:

1. **Why not use/extend an existing schema for the abstractions?**

    For example, STIX [Cyber-observable Objects](https://docs.oasis-open.org/cti/stix/v2.1/cs01/stix-v2.1-cs01.html#_mlbmudhl16lr) (SCO) cover some of the same ground, and link nicely with STIX-formatted intel ... [like ATT&CK itself](https://github.com/oasis-open/cti-python-stix2).  The spec for the objects and their relationships reads a bit like your yaml data sources, and they can be reified with real data.  Seems like STIX SCO is a natural fit, plus it has a well-thought-out relationship model, serialization format, extensions, etc.  
    
    The [Elastic Common Schema](https://github.com/elastic/ecs) (ECS) is great too - it's permissively licensed, available for collaboration on github, has abstractions for many of the examples you provide (users, processes, etc.), and is already powering a lot of searches, visualizations, and analytics.  We see it more in ops contexts, and it's perhaps a bit more flexible than SCOs.  For example, you see it frequently merged with existing event data so you get the benefit of the abstractions without sacrificing the specificity of the original event.

    One of the beautiful things about ATT&CK is it reduced bike-shedding over terminology and helped the infosec community focus - STIX and ECS have put a lot of similar work, seems good to stand on the shoulders of giants.  Naming things is hard, and it takes time to overcome intuitions (even at the top level: _e.g._, to my ear the phrase "data source" connotes the place you get the data, rather than an abstraction of the observable, but I'm just one guy 🙂).
    
    In any case, if ATT&CK leveraged one of these for the abstract entities, seems you could save energy for more ATT&CK-specific work like mapping those to (sub-)techniques or the actual concrete logs/artifacts.  

1. **Are there plans to be more specific about mappings to artifacts?**

    Presumably the idea is that (sub-)techniques would eventually use these new abstract data sources to replace or augment the text in the current "Data Sources" section.  Unfortunately, unless I'm missing something, the proposed model doesn't seem to have a way to capture links to the concrete logs/artifacts.

    For example, the mapping example in figure 13 in part 2 of the blog series illustrates this last step:
    
    ![Data source mapping example](https://miro.medium.com/max/2100/1*5_3b3YlMy-jRGT4vyyILig.jpeg) 
    
    That is, it shows links from the data components to specific event logs on the right, and that last step is _really useful_ ... but it doesn't actually live anywhere in this repo's proposed approach.  For many teams that last leg is the hard part! If we took your schema, for example, maybe added something like:
    
    ```yaml
    - name: Service
      definition: Information about software programs that run in the background ...
      example_artifacts:
        - {os: windows, artifact: Security Audit Event 4688}
        - {os: windows, artifact: Sysmon Event 1}
        - {os: windows, artifact: Prefetch file}
        - {os: linux, artifact: auditd SYSCALL event}
        - {os: linux, artifact: auditd EXECVE event}
        # etc
    ```  
    
    Perhaps this is considered out of scope, but hopefully not; it'd be great to see something as authoritative as ATT&CK pointing folks to specific useful artifacts rather than just the abstraction.  I'd love to hear your thoughts.

Thanks again for your hard work on this and all the related projects, I look forward to learning more!
