### ISSUE TITLE
Support NIDS and WAF via new 'network traffic content' relationship

### ISSUE THREAD

**Issue by hxnoyd** [mitre-attack/attack-datasources#61]
Hello. 

With the new DS structure NIDS and WAF are no longer available. A new relationship could be created in order to improve the mapping with alert related events:

* Data source: Network Traffic
* Data component: network traffic content
* Relationship:
```yaml
  - source_data_element: network traffic        
    relationship: triggered        
    target_data_element: alert
 ```

Thanks in advance.
